INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('JK300','Gudang Showroom Jakarta','WH','WH','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('JK301','Gudang Bulky Jakarta','BLK','WH','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP107','P+ Monkey Forest','PMF','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP113','P+ Tino Ubud','PTN','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP114','P+ Hardys Sanur','HSN','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP117','P+ Seminyak Square','PSS','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP118','P+ Bali Collection','PBC','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP121','P+ Lombok Int','PBL','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP126','P+ Bali Int Landside','BIL','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP127','P+ Bali Int Airside','BIA','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP132','P+ Labuan Bajo Dom','LBJ','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP134','P+ Bintang Seminyak','PBS','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP135','P+ Ubud Market','PUM','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP199','P+ Tunai Bali','','BLI','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP203','P+ Setiabudi','STB','BDG','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP204','P+ BDG Int Husein','BHS','BDG','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP205','P+ BDG Dom Husein','BHD','BDG','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP302','P+ JKT Int T2 DE','PDE','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP308','P+ Plaza Indonesia','PPI','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP310','P+ JKT Dom T2 F','P2F','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP311','P+ Pondok Indah Mall','PIM','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP316','P+ Kelapa Gading Mall','MKG','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP319','P+ Gandaria City','PGC','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP323','P+ Kemang Colony','PK6','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP324','P+ Lotte Shopping Avenue','LSA','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP325','P+ JKT Dom Halim','HPK','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP332','P+JKT Int T3 Gate 09','T09','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP333','P+ JKT Dom T3 Gate 15','T15','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP334','P+ JKT Dom T3 Gate 17','T17','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP337','P+ Plaza Senayan 2','PS2','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP338','P+ JKT Dom Halim 2','HP2','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP339','P+ Senayan City','PSC','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP340','P+ JKT Pier T3','PT3','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP341','P+ Office','POE','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP342','P+ Marketplace Shopee','MPS','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP343','P+ Marketplace Tokopedia','MPT','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP387','P+ E-Commerce Ready Stock','WE2','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP388','P+ E-Commerce','WEB','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP389','Toko Education','','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP390','Gudang Education','','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP399','Direct Selling','Tunai','JKT','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP504','P+ Pakuwon','PKW','SBY','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP509','P+ Galaxy Mall','GLX','SBY','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP515','P+ SBY Dom Juanda 2','JD2','SBY','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP602','P+ Malioboro Mall','PMM','YOG','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP603','P+ SMG Dom Ahmad Yani','BAY','YOG','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP607','P+ JG Dom Adi Sucipto 2','BA2','YOG','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP609','P+ Bandara Intl Yogyakarta','YIA','YOG','--');
INSERT INTO peri_location (location,nama,nick,cabang,am) VALUES ('PP610','P+ Hartono Mall','PHM','YOG','--');
