INSERT INTO peri_kat (kode,nama) VALUES ('0100','Travel & Reference');
INSERT INTO peri_kat (kode,nama) VALUES ('0101','Maps & Atlases');
INSERT INTO peri_kat (kode,nama) VALUES ('0102','Travel Guides');
INSERT INTO peri_kat (kode,nama) VALUES ('0103','Books on Indonesia (Illustrated)');
INSERT INTO peri_kat (kode,nama) VALUES ('0104','Books on Indonesia (Fiction)');
INSERT INTO peri_kat (kode,nama) VALUES ('0105','Books on Indonesia (Non-Fiction)');
INSERT INTO peri_kat (kode,nama) VALUES ('0106','Learning Bahasa Indonesia');
INSERT INTO peri_kat (kode,nama) VALUES ('0107','Language & Reference');
INSERT INTO peri_kat (kode,nama) VALUES ('0108','OFF Blank Card');
INSERT INTO peri_kat (kode,nama) VALUES ('0201','Fiction - New Releases (> Rp 200,000)');
INSERT INTO peri_kat (kode,nama) VALUES ('0202','Fiction - Bestsellers (< Rp 200,000)');
INSERT INTO peri_kat (kode,nama) VALUES ('0203','OFF Science Fiction & Fantasy');
INSERT INTO peri_kat (kode,nama) VALUES ('0204','OFF Asian Literature & Classics');
INSERT INTO peri_kat (kode,nama) VALUES ('0301','Preschool (1-5)');
INSERT INTO peri_kat (kode,nama) VALUES ('0302','Primary (6-10)');
INSERT INTO peri_kat (kode,nama) VALUES ('0303','Young Adult (11+)');
INSERT INTO peri_kat (kode,nama) VALUES ('0304','OFF Origami kits');
INSERT INTO peri_kat (kode,nama) VALUES ('0305','Young Adult');
INSERT INTO peri_kat (kode,nama) VALUES ('0306','(OFF)Origami & Activity');
INSERT INTO peri_kat (kode,nama) VALUES ('0401','Indonesian Cooking');
INSERT INTO peri_kat (kode,nama) VALUES ('0402','Food & Drink');
INSERT INTO peri_kat (kode,nama) VALUES ('0403','Mini Cookbooks');
INSERT INTO peri_kat (kode,nama) VALUES ('0404','Puzzles & Games');
INSERT INTO peri_kat (kode,nama) VALUES ('0405','Crafts, Sewing, Drawing, Coloring');
INSERT INTO peri_kat (kode,nama) VALUES ('0406','Movies, Music, Humor, Celebrities');
INSERT INTO peri_kat (kode,nama) VALUES ('0407','OFF Games + Entertainment');
INSERT INTO peri_kat (kode,nama) VALUES ('0408','OFF Mini Cookbooks (Off)');
INSERT INTO peri_kat (kode,nama) VALUES ('0410','OFF Entertainment (Off)');
INSERT INTO peri_kat (kode,nama) VALUES ('0501','Home Décor, Gardens, Flowers, Architectu');
INSERT INTO peri_kat (kode,nama) VALUES ('0502','OFF Gardening & Flowers');
INSERT INTO peri_kat (kode,nama) VALUES ('0503','Art, Fashion, Jewelry, Lifestyle, Collec');
INSERT INTO peri_kat (kode,nama) VALUES ('0504','Sports, Outdoors & Survival');
INSERT INTO peri_kat (kode,nama) VALUES ('0505','Photography, Automotives, Military & Gra');
INSERT INTO peri_kat (kode,nama) VALUES ('0506','(OFF)Discontinued Illustrated Titles');
INSERT INTO peri_kat (kode,nama) VALUES ('0507','(OFF)Fashion, Celebrities & Weddings');
INSERT INTO peri_kat (kode,nama) VALUES ('0508','(OFF)Entertainment+Craft+Humour');
INSERT INTO peri_kat (kode,nama) VALUES ('0601','New Releases (> Rp 300,000)');
INSERT INTO peri_kat (kode,nama) VALUES ('0602','Business - Bestsellers (< Rp 300,000)');
INSERT INTO peri_kat (kode,nama) VALUES ('0603','OFF Religion & Spirituality');
INSERT INTO peri_kat (kode,nama) VALUES ('0604','OFF Biography, History & Current Affair');
INSERT INTO peri_kat (kode,nama) VALUES ('0605','OFF Relationship & Sex');
INSERT INTO peri_kat (kode,nama) VALUES ('0606','OFF Health & Parenting');
INSERT INTO peri_kat (kode,nama) VALUES ('0607','(OFF)Entertainment+Craft+Humour');
INSERT INTO peri_kat (kode,nama) VALUES ('0701','Religion, Psychology, Science & Spiritua');
INSERT INTO peri_kat (kode,nama) VALUES ('0702','History, Biography, Politics & Current A');
INSERT INTO peri_kat (kode,nama) VALUES ('0703','OFF Biography & Memoirs');
INSERT INTO peri_kat (kode,nama) VALUES ('0704','Health, Fitness, Parenting & Relationshi');
INSERT INTO peri_kat (kode,nama) VALUES ('0801','Postcard');
INSERT INTO peri_kat (kode,nama) VALUES ('0802','Stationary');
INSERT INTO peri_kat (kode,nama) VALUES ('0803','(OFF)Wrapping Paper');
INSERT INTO peri_kat (kode,nama) VALUES ('0804','(OFF)Stamp');
INSERT INTO peri_kat (kode,nama) VALUES ('0806','(OFF)Stationary');
INSERT INTO peri_kat (kode,nama) VALUES ('0901','Imported Magazine');
INSERT INTO peri_kat (kode,nama) VALUES ('0902','Local Magazine');
INSERT INTO peri_kat (kode,nama) VALUES ('0903','Reduced Price Magazine');
INSERT INTO peri_kat (kode,nama) VALUES ('0904','Imported Newspaper');
INSERT INTO peri_kat (kode,nama) VALUES ('0905','Distribution Magazine');
INSERT INTO peri_kat (kode,nama) VALUES ('0906','Local Newspaper');
INSERT INTO peri_kat (kode,nama) VALUES ('1001','Banner');
INSERT INTO peri_kat (kode,nama) VALUES ('1002','Book+Map Cover');
INSERT INTO peri_kat (kode,nama) VALUES ('1003','Gift');
INSERT INTO peri_kat (kode,nama) VALUES ('1004','Local Books in Indonesia');
INSERT INTO peri_kat (kode,nama) VALUES ('1005','Mica Display+Book Display');
INSERT INTO peri_kat (kode,nama) VALUES ('1006','Calendar+Catalogue');
INSERT INTO peri_kat (kode,nama) VALUES ('1008','');
INSERT INTO peri_kat (kode,nama) VALUES ('1009','Drugstore');
INSERT INTO peri_kat (kode,nama) VALUES ('1010','Non Sale');
INSERT INTO peri_kat (kode,nama) VALUES ('1011','Remaindered Titles - Adult');
INSERT INTO peri_kat (kode,nama) VALUES ('1012','Remaindered Titles - Children');
INSERT INTO peri_kat (kode,nama) VALUES ('1013','Cigarettes');
INSERT INTO peri_kat (kode,nama) VALUES ('1014','Cafe Swakelola');
INSERT INTO peri_kat (kode,nama) VALUES ('1101','School');
INSERT INTO peri_kat (kode,nama) VALUES ('1102','School Reference');
INSERT INTO peri_kat (kode,nama) VALUES ('1103','School etext');
INSERT INTO peri_kat (kode,nama) VALUES ('1104','OFF Café');
INSERT INTO peri_kat (kode,nama) VALUES ('1105','OFF');
INSERT INTO peri_kat (kode,nama) VALUES ('1107','OFF');
INSERT INTO peri_kat (kode,nama) VALUES ('1108','OFF');
INSERT INTO peri_kat (kode,nama) VALUES ('1201','HED - Text');
INSERT INTO peri_kat (kode,nama) VALUES ('1202','HED - Reference');
INSERT INTO peri_kat (kode,nama) VALUES ('1203','HED -  etext');
INSERT INTO peri_kat (kode,nama) VALUES ('1204','(OFF) HED Ref- Accounting, Fin');
INSERT INTO peri_kat (kode,nama) VALUES ('1205','(OFF) HED - Engineering, Compu');
INSERT INTO peri_kat (kode,nama) VALUES ('1206','(OFF) HED Ref- Engineering, Co');
INSERT INTO peri_kat (kode,nama) VALUES ('1207','(OFF) HED - Soc Science, Human');
INSERT INTO peri_kat (kode,nama) VALUES ('1208','(OFF) HED Ref- Economics, Busi');
INSERT INTO peri_kat (kode,nama) VALUES ('1209','(OFF) HED - Life Science / MIP');
INSERT INTO peri_kat (kode,nama) VALUES ('1210','(OFF) HED Ref- Life Science /');
INSERT INTO peri_kat (kode,nama) VALUES ('1211','(OFF) HED - Medical');
INSERT INTO peri_kat (kode,nama) VALUES ('1212','(OFF) HED Ref- Medical');
INSERT INTO peri_kat (kode,nama) VALUES ('1213','(OFF) HED - Design, Visual, Ar');
INSERT INTO peri_kat (kode,nama) VALUES ('1214','(OFF) HED Ref- Design, Visual,');
INSERT INTO peri_kat (kode,nama) VALUES ('1215','(OFF) HED');
INSERT INTO peri_kat (kode,nama) VALUES ('1216','(OFF) HED Ref -');
INSERT INTO peri_kat (kode,nama) VALUES ('1217','(OFF) HED');
INSERT INTO peri_kat (kode,nama) VALUES ('1218','(OFF) HED Ref -');
INSERT INTO peri_kat (kode,nama) VALUES ('1219','(OFF) HED Ref -');
INSERT INTO peri_kat (kode,nama) VALUES ('1220','(OFF) ELT Kinder');
INSERT INTO peri_kat (kode,nama) VALUES ('1221','(OFF) ELT Pri');
INSERT INTO peri_kat (kode,nama) VALUES ('1222','(OFF) ELT Sec');
INSERT INTO peri_kat (kode,nama) VALUES ('1223','(OFF) ELT Adult & Bus');
INSERT INTO peri_kat (kode,nama) VALUES ('1224','(OFF) ELT Text Exam Prep');
INSERT INTO peri_kat (kode,nama) VALUES ('1225','(OFF) ELT Skills & Dict');
INSERT INTO peri_kat (kode,nama) VALUES ('1226','(OFF) ELT Teacher Ref & Dev');
INSERT INTO peri_kat (kode,nama) VALUES ('1227','(OFF) ELT ESP');
INSERT INTO peri_kat (kode,nama) VALUES ('1228','(OFF) ELT');
INSERT INTO peri_kat (kode,nama) VALUES ('1230','(OFF) Sch Text Kinder - Kinder');
INSERT INTO peri_kat (kode,nama) VALUES ('1231','(OFF) Sch Text Pri - Primary T');
INSERT INTO peri_kat (kode,nama) VALUES ('1232','(OFF) Sch Text Pri - Primary R');
INSERT INTO peri_kat (kode,nama) VALUES ('1233','(OFF) Sch Text Pri - Primary M');
INSERT INTO peri_kat (kode,nama) VALUES ('1234','(OFF) Sch Text Pri - Primary S');
INSERT INTO peri_kat (kode,nama) VALUES ('1235','(OFF) Sch Text Pri - Primary S');
INSERT INTO peri_kat (kode,nama) VALUES ('1236','(OFF) Sch Text Pri - Primary E');
INSERT INTO peri_kat (kode,nama) VALUES ('1237','(OFF) Sch Text Pri -');
INSERT INTO peri_kat (kode,nama) VALUES ('1238','(OFF) Sch Text Pri -');
INSERT INTO peri_kat (kode,nama) VALUES ('1240','(OFF) Sch Text Sec-Sec Test &');
INSERT INTO peri_kat (kode,nama) VALUES ('1241','(OFF) Sch Text Sec - Sec Reade');
INSERT INTO peri_kat (kode,nama) VALUES ('1242','(OFF) Sch Text Sec - Sec Math');
INSERT INTO peri_kat (kode,nama) VALUES ('1243','(OFF) Sch Text Sec - Sec Sci');
INSERT INTO peri_kat (kode,nama) VALUES ('1244','(OFF) Sch Text Sec - Sec Socia');
INSERT INTO peri_kat (kode,nama) VALUES ('1245','(OFF) Sch Text Sec - Sec Engli');
INSERT INTO peri_kat (kode,nama) VALUES ('1246','(OFF) Sch Text Sec -');
INSERT INTO peri_kat (kode,nama) VALUES ('1247','(OFF) Sch Text Sec -');
INSERT INTO peri_kat (kode,nama) VALUES ('1248','(OFF) Sch Text Sec -');
INSERT INTO peri_kat (kode,nama) VALUES ('1249','(OFF) Sch Text Sec -');
INSERT INTO peri_kat (kode,nama) VALUES ('1250','(OFF) Junior College-Sec Test');
INSERT INTO peri_kat (kode,nama) VALUES ('1251','(OFF) Junior College-Sec Reade');
INSERT INTO peri_kat (kode,nama) VALUES ('1252','(OFF) Sch Ref Sec -');
INSERT INTO peri_kat (kode,nama) VALUES ('1253','(OFF) Junior College-Sec Sci');
INSERT INTO peri_kat (kode,nama) VALUES ('1254','(OFF) Junior College-Sec Socia');
INSERT INTO peri_kat (kode,nama) VALUES ('1255','(OFF) Junior College-Sec Engli');
INSERT INTO peri_kat (kode,nama) VALUES ('1256','(OFF) Junior College-');
INSERT INTO peri_kat (kode,nama) VALUES ('1257','(OFF) Junior College-');
INSERT INTO peri_kat (kode,nama) VALUES ('1260','(OFF) ETEXT / EBOOK-Economics,');
INSERT INTO peri_kat (kode,nama) VALUES ('1261','(OFF) ETEXT / EBOOK-Accounting');
INSERT INTO peri_kat (kode,nama) VALUES ('1262','(OFF) ETEXT / EBOOK-Engineerin');
INSERT INTO peri_kat (kode,nama) VALUES ('1263','(OFF) ETEXT / EBOOK-Soc Scienc');
INSERT INTO peri_kat (kode,nama) VALUES ('1264','(OFF) ETEXT / EBOOK-Life Scien');
INSERT INTO peri_kat (kode,nama) VALUES ('1265','(OFF) ETEXT / EBOOK-Medical');
INSERT INTO peri_kat (kode,nama) VALUES ('1266','(OFF) ETEXT / EBOOK-Design, Vi');
INSERT INTO peri_kat (kode,nama) VALUES ('1267','(OFF) xx');
INSERT INTO peri_kat (kode,nama) VALUES ('1268','(OFF) xx');
INSERT INTO peri_kat (kode,nama) VALUES ('1269','(OFF) xx');
INSERT INTO peri_kat (kode,nama) VALUES ('1299','(OFF) EDU Other');
INSERT INTO peri_kat (kode,nama) VALUES ('1301','Children Toys - Girls');
INSERT INTO peri_kat (kode,nama) VALUES ('1302','Children Toys - Boys');
INSERT INTO peri_kat (kode,nama) VALUES ('1303','Children Toys - IPS');
INSERT INTO peri_kat (kode,nama) VALUES ('1304','Children Toys - EMCO');
INSERT INTO peri_kat (kode,nama) VALUES ('1305','Children Toys - GAME&CRAFT');
INSERT INTO peri_kat (kode,nama) VALUES ('1306','NN');
INSERT INTO peri_kat (kode,nama) VALUES ('1310','OFF Parker');
INSERT INTO peri_kat (kode,nama) VALUES ('1311','OFF');
INSERT INTO peri_kat (kode,nama) VALUES ('1320','Skybags');
INSERT INTO peri_kat (kode,nama) VALUES ('1401','SALAD');
INSERT INTO peri_kat (kode,nama) VALUES ('1402','SNACK');
INSERT INTO peri_kat (kode,nama) VALUES ('1403','MAYONNAISE');
INSERT INTO peri_kat (kode,nama) VALUES ('1404','SOUP');
INSERT INTO peri_kat (kode,nama) VALUES ('1405','SUSHI');
INSERT INTO peri_kat (kode,nama) VALUES ('1406','RICE DISH');
INSERT INTO peri_kat (kode,nama) VALUES ('1407','PASTA DISH');
INSERT INTO peri_kat (kode,nama) VALUES ('1408','HOT DOG');
INSERT INTO peri_kat (kode,nama) VALUES ('1409','DESSERT');
INSERT INTO peri_kat (kode,nama) VALUES ('1410','PASTRY');
INSERT INTO peri_kat (kode,nama) VALUES ('1411','PASTRY CONTD');
INSERT INTO peri_kat (kode,nama) VALUES ('1420','COFFEE');
INSERT INTO peri_kat (kode,nama) VALUES ('1421','SIGNATURE ICE CREMALATTE');
INSERT INTO peri_kat (kode,nama) VALUES ('1422','GRIFON ARTISAN ICE SHAKEN LEMONADE');
INSERT INTO peri_kat (kode,nama) VALUES ('1423','FRESH JUICE');
INSERT INTO peri_kat (kode,nama) VALUES ('1424','BOTTLED BEVERAGES');
INSERT INTO peri_kat (kode,nama) VALUES ('1499','OFF - Pindahan dari 11xx');
INSERT INTO peri_kat (kode,nama) VALUES ('1501','Meteor TY');
INSERT INTO peri_kat (kode,nama) VALUES ('1502','By Design');
INSERT INTO peri_kat (kode,nama) VALUES ('1503','Bariel & Co');
INSERT INTO peri_kat (kode,nama) VALUES ('1504','Epoch Blooming Toys');
INSERT INTO peri_kat (kode,nama) VALUES ('1505','MAP Aktif Perkasa');
INSERT INTO peri_kat (kode,nama) VALUES ('1506','Multitren Indo');
INSERT INTO peri_kat (kode,nama) VALUES ('1509','OFF Others - TA');
INSERT INTO peri_kat (kode,nama) VALUES ('1510','OFF Toys - Firm');
INSERT INTO peri_kat (kode,nama) VALUES ('1511','OFF ALJ Indonesia');
INSERT INTO peri_kat (kode,nama) VALUES ('1512','OFF Emway');
INSERT INTO peri_kat (kode,nama) VALUES ('1513','OFF Funbricks');
INSERT INTO peri_kat (kode,nama) VALUES ('1514','OFF By Design');
INSERT INTO peri_kat (kode,nama) VALUES ('1515','OFF MAP');
INSERT INTO peri_kat (kode,nama) VALUES ('1516','OFF Origami kits');
INSERT INTO peri_kat (kode,nama) VALUES ('1517','OFF Indopassion');
INSERT INTO peri_kat (kode,nama) VALUES ('1518','OFF Manconesia');
INSERT INTO peri_kat (kode,nama) VALUES ('1519','OFF Others - Toys');
INSERT INTO peri_kat (kode,nama) VALUES ('1521','OFF Notebooks');
INSERT INTO peri_kat (kode,nama) VALUES ('1522','OFF Ballpens + Marker Pens');
INSERT INTO peri_kat (kode,nama) VALUES ('1523','OFF Playing Cards + Note Cards');
INSERT INTO peri_kat (kode,nama) VALUES ('1524','OFF Postcards');
INSERT INTO peri_kat (kode,nama) VALUES ('1525','OFF Gift Wrapping Paper');
INSERT INTO peri_kat (kode,nama) VALUES ('1526','OFF Origami paper packs');
INSERT INTO peri_kat (kode,nama) VALUES ('1529','OFF Others - Stationery');
INSERT INTO peri_kat (kode,nama) VALUES ('1599','Others Toys');
INSERT INTO peri_kat (kode,nama) VALUES ('1601','TP Leonard');
INSERT INTO peri_kat (kode,nama) VALUES ('1602','TP DQ');
INSERT INTO peri_kat (kode,nama) VALUES ('1603','TP Aligator');
INSERT INTO peri_kat (kode,nama) VALUES ('1604','TP Periplus Travel Pro');
INSERT INTO peri_kat (kode,nama) VALUES ('1605','Goesar');
INSERT INTO peri_kat (kode,nama) VALUES ('1606','Periplus Tote Bag');
INSERT INTO peri_kat (kode,nama) VALUES ('1607','Travel Bag Leonard');
INSERT INTO peri_kat (kode,nama) VALUES ('1608','Travel Bag Prairie Dog');
INSERT INTO peri_kat (kode,nama) VALUES ('1609','TA Travel Blue');
INSERT INTO peri_kat (kode,nama) VALUES ('1610','Hydration Bottle');
INSERT INTO peri_kat (kode,nama) VALUES ('1611','Periplus Masker');
INSERT INTO peri_kat (kode,nama) VALUES ('1612','KNS ( Cons )');
INSERT INTO peri_kat (kode,nama) VALUES ('1699','Others Travel Accessories');
INSERT INTO peri_kat (kode,nama) VALUES ('1701','Faber Castell');
INSERT INTO peri_kat (kode,nama) VALUES ('1702','Global Dinamika Indonesia');
INSERT INTO peri_kat (kode,nama) VALUES ('1703','Sahabat Utama');
INSERT INTO peri_kat (kode,nama) VALUES ('1704','Playing Cards + Note Cards');
INSERT INTO peri_kat (kode,nama) VALUES ('1705','Gift Wrapping Paper');
INSERT INTO peri_kat (kode,nama) VALUES ('1706','Origami');
INSERT INTO peri_kat (kode,nama) VALUES ('1707','Karya Creative');
INSERT INTO peri_kat (kode,nama) VALUES ('1708','SAMB');
INSERT INTO peri_kat (kode,nama) VALUES ('1709','PT Halodata');
INSERT INTO peri_kat (kode,nama) VALUES ('1710','Nila Tanzil Collection');
INSERT INTO peri_kat (kode,nama) VALUES ('1711','Aladdin Sarana Indonesia PT');
INSERT INTO peri_kat (kode,nama) VALUES ('1799','Others Stationery');
INSERT INTO peri_kat (kode,nama) VALUES ('1801','Mitra Kios HP accessories');
INSERT INTO peri_kat (kode,nama) VALUES ('1802','Freshindo HP accessories');
INSERT INTO peri_kat (kode,nama) VALUES ('1803','Urban Ritel HP accessories');
INSERT INTO peri_kat (kode,nama) VALUES ('1804','Integritas Dinamika HP acc');
INSERT INTO peri_kat (kode,nama) VALUES ('1805','Trimitra HP Accessories');
INSERT INTO peri_kat (kode,nama) VALUES ('1806','Selaras Makmur Sejati');
INSERT INTO peri_kat (kode,nama) VALUES ('1807','Digital Inovasi Indonesia');
INSERT INTO peri_kat (kode,nama) VALUES ('1808','Lexingham');
INSERT INTO peri_kat (kode,nama) VALUES ('1809','Sumber Sejahtera Audiotama');
INSERT INTO peri_kat (kode,nama) VALUES ('1810','MPOW Indonesia');
INSERT INTO peri_kat (kode,nama) VALUES ('OTHR','');
